apiVersion: dashboard.jenkins.crossplane.io/v1alpha1
kind: Job
metadata:
  name: job-example
spec:
  forProvider:
    name: Jan27Test1
    parent: Testf
    config: "<?xml version=\"1.1\" encoding=\"UTF-8\"?><project>\n  <description/>\n  <keepDependencies>false</keepDependencies>\n  <properties/>\n  <scm class=\"hudson.scm.NullSCM\"/>\n  <canRoam>true</canRoam>\n  <disabled>false</disabled>\n  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>\n  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>\n  <triggers/>\n  <concurrentBuild>false</concurrentBuild>\n  <builders/>\n  <publishers/>\n  <buildWrappers/>\n</project>"
  providerConfigRef:
    name: provider-jenkins-config