apiVersion: jenkins.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-jenkins-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: jenkins-provider-secret
      key: credentials
  username: "caner"
  baseurl: "http://3.89.89.181:8080/"
